-- Author :       Jorge A. Rodríguez Campos
-- Target DBMS : Generic DBMS
--


-- 
-- TABLE: AUTOR 
--

CREATE TABLE AUTOR(
    AUTOR_ID            IDENTITY,
    NOMBRE              VARCHAR(50)       NOT NULL,
    APELLIDO_PATERNO    VARCHAR(50)       NOT NULL,
    APELLIDO_MATERNO    VARCHAR(50),
    PRIMARY KEY (AUTOR_ID)
)
;



-- 
-- TABLE: EDITORIAL 
--

CREATE TABLE EDITORIAL(
    EDITORIAL_ID    DECIMAL(4, 0)    NOT NULL,
    NOMBRE          VARCHAR(100)     NOT NULL,
    ACTIVO          BIT              NOT NULL,
    PRIMARY KEY (EDITORIAL_ID)
)
;



-- 
-- TABLE: STATUS_LIBRO 
--

CREATE TABLE STATUS_LIBRO(
    STATUS_LIBRO_ID    DECIMAL(2, 0)    NOT NULL,
    CLAVE              VARCHAR(50)      NOT NULL,
    DESCRIPCION        VARCHAR(500)     NOT NULL,
    ACTIVO             BIT              NOT NULL,
    PRIMARY KEY (STATUS_LIBRO_ID)
)
;



-- 
-- TABLE: LIBRO 
--

CREATE TABLE LIBRO(
    LIBRO_ID                IDENTITY,
    TITULO                  VARCHAR(100)      NOT NULL,
    EDICION                 DECIMAL(2, 0)     NOT NULL,
    ISBN                    VARCHAR(100)      NOT NULL,
    CODIGO_COLOR            VARCHAR(6)        NOT NULL,
    CODIGO_CLASIFICACION    VARCHAR(100)      NOT NULL,
    NUMERO_EJEMPLARES       DECIMAL(4, 0)     NOT NULL,
    PRECIO_VENTA            DECIMAL(6, 2)     NOT NULL,
    EDITORIAL_ID            DECIMAL(4, 0)     NOT NULL,
    STATUS_LIBRO_ID         DECIMAL(2, 0)     NOT NULL,
    PRIMARY KEY (LIBRO_ID), 
    FOREIGN KEY (EDITORIAL_ID)
    REFERENCES EDITORIAL(EDITORIAL_ID),
    FOREIGN KEY (STATUS_LIBRO_ID)
    REFERENCES STATUS_LIBRO(STATUS_LIBRO_ID)
)
;



-- 
-- TABLE: AUTOR_LIBRO 
--

CREATE TABLE AUTOR_LIBRO(
    AUTOR_LIBRO_ID    IDENTITY,
    LIBRO_ID          DECIMAL(10, 0)    NOT NULL,
    AUTOR_ID          DECIMAL(10, 0)    NOT NULL,
    PRIMARY KEY (AUTOR_LIBRO_ID), 
    FOREIGN KEY (LIBRO_ID)
    REFERENCES LIBRO(LIBRO_ID),
    FOREIGN KEY (AUTOR_ID)
    REFERENCES AUTOR(AUTOR_ID)
)
;



-- 
-- TABLE: BANCO 
--

CREATE TABLE BANCO(
    BANCO_ID     DECIMAL(3, 0)    NOT NULL,
    NOMBRE       VARCHAR(50)      NOT NULL,
    URL_CARGO    VARCHAR(1000)    NOT NULL,
    PRIMARY KEY (BANCO_ID)
)
;



-- 
-- TABLE: CATEGORIA 
--

CREATE TABLE CATEGORIA(
    CATEGORIA_ID    DECIMAL(2, 0)    NOT NULL,
    CLAVE           VARCHAR(50)      NOT NULL,
    DESCRIPCION     VARCHAR(500)     NOT NULL,
    ACTIVO          BIT              NOT NULL,
    PRIMARY KEY (CATEGORIA_ID)
)
;



-- 
-- TABLE: CATEGORIA_LIBRO 
--

CREATE TABLE CATEGORIA_LIBRO(
    CATEGORIA_LIBRO_ID    IDENTITY,
    CATEGORIA_ID          DECIMAL(2, 0)     NOT NULL,
    LIBRO_ID              DECIMAL(10, 0)    NOT NULL,
    PRIMARY KEY (CATEGORIA_LIBRO_ID), 
    FOREIGN KEY (CATEGORIA_ID)
    REFERENCES CATEGORIA(CATEGORIA_ID),
    FOREIGN KEY (LIBRO_ID)
    REFERENCES LIBRO(LIBRO_ID)
)
;



-- 
-- TABLE: TIPO_CLIENTE 
--

CREATE TABLE TIPO_CLIENTE(
    TIPO_CLIENTE_ID    DECIMAL(2, 0)    NOT NULL,
    CLAVE              VARCHAR(50)      NOT NULL,
    DESCRIPCION        VARCHAR(500)     NOT NULL,
    ACTIVO             BIT              NOT NULL,
    PRIMARY KEY (TIPO_CLIENTE_ID)
)
;



-- 
-- TABLE: CLIENTE 
--

CREATE TABLE CLIENTE(
    CLIENTE_ID              IDENTITY,
    CLIENTE_FRECUENTE_ID    DECIMAL(10, 0)        NULL,
    NOMBRE                  VARCHAR(50)       NOT NULL,
    APELLIDO_PATERNO        VARCHAR(50)       NOT NULL,
    APELLIDO_MATERNO        VARCHAR(50),
    EMAIL                   VARCHAR(250)      NOT NULL,
    RFC                     VARCHAR(13)       NOT NULL,
    DIRECCION               VARCHAR(30)       NOT NULL,
    TELEFONO                VARCHAR(20)       NOT NULL,
    USUARIO                 VARCHAR(15)       NOT NULL,
    PASSWORD                VARCHAR(15)       NOT NULL,
    TIPO_CLIENTE_ID         DECIMAL(2, 0)     NOT NULL,
    PRIMARY KEY (CLIENTE_ID), 
    FOREIGN KEY (TIPO_CLIENTE_ID)
    REFERENCES TIPO_CLIENTE(TIPO_CLIENTE_ID)
)
;



-- 
-- TABLE: STATUS_ORDEN 
--

CREATE TABLE STATUS_ORDEN(
    STATUS_ORDEN_ID    DECIMAL(2, 0)    NOT NULL,
    CLAVE              VARCHAR(50)      NOT NULL,
    DESCRIPCION        VARCHAR(500)     NOT NULL,
    ACTIVO             BIT              NOT NULL,
    PRIMARY KEY (STATUS_ORDEN_ID)
)
;



-- 
-- TABLE: ORDEN_COMPRA 
--

CREATE TABLE ORDEN_COMPRA(
    ORDEN_COMPRA_ID            IDENTITY,
    FECHA_STATUS               TIME              NOT NULL,
    SEGUIMIENTO_ENTREGA_ID  VARCHAR(100)      NOT NULL,
    CLIENTE_ID                 DECIMAL(10, 0)    NOT NULL,
    STATUS_ORDEN_ID            DECIMAL(2, 0)     NOT NULL,
    PRIMARY KEY (ORDEN_COMPRA_ID), 
    FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID),
    FOREIGN KEY (STATUS_ORDEN_ID)
    REFERENCES STATUS_ORDEN(STATUS_ORDEN_ID)
)
;



-- 
-- TABLE: PROMOCION 
--

CREATE TABLE PROMOCION(
    PROMOCION_ID    IDENTITY,
    NOMBRE          VARCHAR(50)       NOT NULL,
    DESCRIPCION     VARCHAR(1000)     NOT NULL,
    EXPRESION       VARCHAR(1000)     NOT NULL,
    DESCUENTO       DECIMAL(6, 2)     NOT NULL,
    FECHA_INICIO    TIME              NOT NULL,
    FECHA_FIN       TIME              NOT NULL,
    PRIMARY KEY (PROMOCION_ID)
)
;



-- 
-- TABLE: DETALLE_ORDEN 
--

CREATE TABLE DETALLE_ORDEN(
    DETALLE_ORDEN_ID    IDENTITY,
    CANTIDAD            DECIMAL(4, 0)     NOT NULL,
    COSTO_UNITARIO      DECIMAL(6, 2)     NOT NULL,
    ORDEN_COMPRA_ID     DECIMAL(10, 0)    NOT NULL,
    LIBRO_ID            DECIMAL(10, 0)    NOT NULL,
    PROMOCION_ID        DECIMAL(10, 0)    NOT NULL,
    PRIMARY KEY (DETALLE_ORDEN_ID), 
    FOREIGN KEY (ORDEN_COMPRA_ID)
    REFERENCES ORDEN_COMPRA(ORDEN_COMPRA_ID),
    FOREIGN KEY (LIBRO_ID)
    REFERENCES LIBRO(LIBRO_ID),
    FOREIGN KEY (PROMOCION_ID)
    REFERENCES PROMOCION(PROMOCION_ID)
)
;



-- 
-- TABLE: STATUS_PEDIDO 
--

CREATE TABLE STATUS_PEDIDO(
    STATUS_PEDIDO_ID    DECIMAL(2, 0)    NOT NULL,
    CLAVE               VARCHAR(50)      NOT NULL,
    DESCRIPCION         VARCHAR(500)     NOT NULL,
    ACTIVO              BIT              NOT NULL,
    PRIMARY KEY (STATUS_PEDIDO_ID)
)
;



-- 
-- TABLE: PEDIDO 
--

CREATE TABLE PEDIDO(
    PEDIDO_ID                    IDENTITY,
    FECHA_STATUS                 TIME              NOT NULL,
    FECHA_ESTIMADA_RECEPCOION    TIME              NOT NULL,
    STATUS_PEDIDO_ID             DECIMAL(2, 0)     NOT NULL,
    PRIMARY KEY (PEDIDO_ID), 
    FOREIGN KEY (STATUS_PEDIDO_ID)
    REFERENCES STATUS_PEDIDO(STATUS_PEDIDO_ID)
)
;



-- 
-- TABLE: PROVEEDOR 
--

CREATE TABLE PROVEEDOR(
    PROVEEDOR_ID    IDENTITY,
    NOMBRE          VARCHAR(100)     NOT NULL,
    DIRECCION       VARCHAR(1000)    NOT NULL,
    URL_PEDIDOS     VARCHAR(1000)    NOT NULL,
    PRIMARY KEY (PROVEEDOR_ID)
)
;



-- 
-- TABLE: PROVEEDOR_LIBRO 
--

CREATE TABLE PROVEEDOR_LIBRO(
    PROVEEDOR_LIBRO_ID    IDENTITY,
    PROVEEDOR_ID          DECIMAL(5, 0)     NOT NULL,
    LIBRO_ID              DECIMAL(10, 0)    NOT NULL,
    PRIMARY KEY (PROVEEDOR_LIBRO_ID), 
    FOREIGN KEY (PROVEEDOR_ID)
    REFERENCES PROVEEDOR(PROVEEDOR_ID),
    FOREIGN KEY (LIBRO_ID)
    REFERENCES LIBRO(LIBRO_ID)
)
;



-- 
-- TABLE: DETALLE_PEDIDO 
--

CREATE TABLE DETALLE_PEDIDO(
    DETALLE_PEDIDO_ID      IDENTITY,
    CANTIDAD_SOLICITADA    DECIMAL(4, 0)     NOT NULL,
    CANTIDAD_RECIBIDA      DECIMAL(4, 0),
    PRECIO_COMPRA          DECIMAL(6, 2)     NOT NULL,
    LIBRO_ID               DECIMAL(10, 0)    NOT NULL,
    PROVEEDOR_LIBRO_ID     DECIMAL(10, 0)    NOT NULL,
    PEDIDO_ID              DECIMAL(10, 0)    NOT NULL,
    PRIMARY KEY (DETALLE_PEDIDO_ID), 
    FOREIGN KEY (PEDIDO_ID)
    REFERENCES PEDIDO(PEDIDO_ID),
    FOREIGN KEY (LIBRO_ID)
    REFERENCES LIBRO(LIBRO_ID),
    FOREIGN KEY (PROVEEDOR_LIBRO_ID)
    REFERENCES PROVEEDOR_LIBRO(PROVEEDOR_LIBRO_ID)
)
;



-- 
-- TABLE: FACTURA 
--

CREATE TABLE FACTURA(
    FACTURA_ID         IDENTITY,
    FECHA_FACTURA      TIME              NOT NULL,
    SELLO_DIGITAL      VARCHAR(1000)     NOT NULL,
    ORDEN_COMPRA_ID    DECIMAL(10, 0)    NOT NULL,
    PRIMARY KEY (FACTURA_ID), 
    FOREIGN KEY (ORDEN_COMPRA_ID)
    REFERENCES ORDEN_COMPRA(ORDEN_COMPRA_ID)
)
;



-- 
-- TABLE: HISTORICO_STATUS_ORDEN 
--

CREATE TABLE HISTORICO_STATUS_ORDEN(
    HISTORICO_STATUS_ORDEN_ID    IDENTITY,
    FECHA_STATUS                 DATE              NOT NULL,
    ORDEN_COMPRA_ID              DECIMAL(10, 0)    NOT NULL,
    STATUS_ORDEN_ID              DECIMAL(2, 0)     NOT NULL,
    PRIMARY KEY (HISTORICO_STATUS_ORDEN_ID), 
    FOREIGN KEY (ORDEN_COMPRA_ID)
    REFERENCES ORDEN_COMPRA(ORDEN_COMPRA_ID),
    FOREIGN KEY (STATUS_ORDEN_ID)
    REFERENCES STATUS_ORDEN(STATUS_ORDEN_ID)
)
;



-- 
-- TABLE: HISTORICO_STATUS_PEDIDO 
--

CREATE TABLE HISTORICO_STATUS_PEDIDO(
    HISTORICO_STATUS_PEDIDO_ID    IDENTITY,
    FECHA_STATUS                  DATE              NOT NULL,
    PEDIDO_ID                     DECIMAL(10, 0)    NOT NULL,
    STATUS_PEDIDO_ID              DECIMAL(2, 0)     NOT NULL,
    PRIMARY KEY (HISTORICO_STATUS_PEDIDO_ID), 
    FOREIGN KEY (PEDIDO_ID)
    REFERENCES PEDIDO(PEDIDO_ID),
    FOREIGN KEY (STATUS_PEDIDO_ID)
    REFERENCES STATUS_PEDIDO(STATUS_PEDIDO_ID)
)
;



-- 
-- TABLE: IMAGEN_LIBRO 
--

CREATE TABLE IMAGEN_LIBRO(
    IMAGEN_LIBRO_ID    IDENTITY,
    NUM_IMAGEN         DECIMAL(2, 0)      NOT NULL,
    IMAGEN             BLOB    NOT NULL,
    LIBRO_ID           DECIMAL(10, 0)     NOT NULL,
    PRIMARY KEY (IMAGEN_LIBRO_ID), 
    FOREIGN KEY (LIBRO_ID)
    REFERENCES LIBRO(LIBRO_ID)
)
;



-- 
-- TABLE: TIPO_TARJETA 
--

CREATE TABLE TIPO_TARJETA(
    TIPO_TARJETA_ID    DECIMAL(2, 0)    NOT NULL,
    CLAVE              VARCHAR(50)      NOT NULL,
    DESCRIPCION        VARCHAR(500)     NOT NULL,
    ACTIVO             BIT              NOT NULL,
    PRIMARY KEY (TIPO_TARJETA_ID)
)
;



-- 
-- TABLE: TARJETA_CREDITO 
--

CREATE TABLE TARJETA_CREDITO(
    TARJETA_CREDITO_ID    IDENTITY,
    NUMERO_TARJETA        VARCHAR(16)       NOT NULL,
    MES_EXPIRACION        VARCHAR(2)        NOT NULL,
    ANIO_EXPIRACION       VARCHAR(32)       NOT NULL,
    NUMERO_SEGURIDAD      VARCHAR(30)       NOT NULL,
    CLIENTE_ID            DECIMAL(10, 0)    NOT NULL,
    BANCO_ID              DECIMAL(3, 0)     NOT NULL,
    TIPO_TARJETA_ID       DECIMAL(2, 0)     NOT NULL,
    PRIMARY KEY (TARJETA_CREDITO_ID), 
    FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID),
    FOREIGN KEY (BANCO_ID)
    REFERENCES BANCO(BANCO_ID),
    FOREIGN KEY (TIPO_TARJETA_ID)
    REFERENCES TIPO_TARJETA(TIPO_TARJETA_ID)
)
;




