--TIPO_CLIENTE
INSERT INTO TIPO_CLIENTE(TIPO_CLIENTE_ID, CLAVE,DESCRIPCION,ACTIVO) VALUES(1,'AFICIONADO','CON 5 O MENOS LIBROS COMPRADOS',true);
INSERT INTO TIPO_CLIENTE(TIPO_CLIENTE_ID, CLAVE,DESCRIPCION,ACTIVO) VALUES(2,'APASIONADO','ENTRE 6 Y 15 LIBROS COMPRADOS',true);
INSERT INTO TIPO_CLIENTE(TIPO_CLIENTE_ID, CLAVE,DESCRIPCION,ACTIVO) VALUES(3,'ADICTO','MAS DE 15 LIBROS COMPRADOS',true);


--TIPO_TARJETA
INSERT INTO TIPO_TARJETA(TIPO_TARJETA_ID, CLAVE,DESCRIPCION,ACTIVO) VALUES(1,'VISA','VISA',true);
INSERT INTO TIPO_TARJETA(TIPO_TARJETA_ID, CLAVE,DESCRIPCION,ACTIVO) VALUES(2,'MASTER CARD','MASTERD CARD',true);
INSERT INTO TIPO_TARJETA(TIPO_TARJETA_ID, CLAVE,DESCRIPCION,ACTIVO) VALUES(3,'AMERICAN EXPRESS','AMERICAN EXPRESS',true);


--STATUS_PEDIDO
INSERT INTO STATUS_PEDIDO(STATUS_PEDIDO_ID, CLAVE,DESCRIPCION,ACTIVO) VALUES(1,'REGISTRADO','',true);
INSERT INTO STATUS_PEDIDO(STATUS_PEDIDO_ID, CLAVE,DESCRIPCION,ACTIVO) VALUES(2,'ENVIADO AL PROVEEDOR','ENVIADO AL PROVEEDOR',true);
INSERT INTO STATUS_PEDIDO(STATUS_PEDIDO_ID, CLAVE,DESCRIPCION,ACTIVO) VALUES(3,'RECIBIDO','RECIBIDO',true);

-- STATUS_ORDEN
INSERT INTO STATUS_ORDEN(STATUS_ORDEN_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(1, 'REGISTRADA', 'REGISTRADA', true);
INSERT INTO STATUS_ORDEN(STATUS_ORDEN_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(2, 'PAGO EN VALIDACION', 'PAGO EN VALIDACION', true);
INSERT INTO STATUS_ORDEN(STATUS_ORDEN_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(3, 'PAGO REALIZADO', 'PAGO REALIZADO', true);
INSERT INTO STATUS_ORDEN(STATUS_ORDEN_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(4, 'ENVIADA A PAQUETERIA', 'ENVIADA A PAQUETERIA', true);

-- STATUS_LIBRO
INSERT INTO STATUS_LIBRO(STATUS_LIBRO_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(1, 'DISPONIBLE', 'DISPONIBLE', true);
INSERT INTO STATUS_LIBRO(STATUS_LIBRO_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(2, 'EN PEDIDO', 'EN PEDIDO', true);
INSERT INTO STATUS_LIBRO(STATUS_LIBRO_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(3, 'BAJA', 'BAJA', true);
INSERT INTO STATUS_LIBRO(STATUS_LIBRO_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(4, 'AGOTADO', 'AGOTADO', true);


--CATEGORIA
INSERT INTO CATEGORIA(CATEGORIA_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(1, 'ANIMALES Y MASCOTAS', 'ANIMALES Y MASCOTAS', true);
INSERT INTO CATEGORIA(CATEGORIA_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(2, 'CIENCIAS NATURALES', 'CIENCIAS NATURALES', true);
INSERT INTO CATEGORIA(CATEGORIA_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(3, 'CIENCIAS SOCIALES', 'CIENCIAS SOCIALES', true);
INSERT INTO CATEGORIA(CATEGORIA_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(4, 'CONTABILIDAD', 'CONTABILIDAD', true);
INSERT INTO CATEGORIA(CATEGORIA_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(5, 'DERECHO', 'DERECHO', true);
INSERT INTO CATEGORIA(CATEGORIA_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(6, 'ESOTERISMO', 'ESOTERISMO', true);
INSERT INTO CATEGORIA(CATEGORIA_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(7, 'FILOSOFIA', 'FILOSOFIA', true);
INSERT INTO CATEGORIA(CATEGORIA_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(8, 'GASTRONOMIA', 'GASTRONOMIA', true);
INSERT INTO CATEGORIA(CATEGORIA_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(9, 'GEOGRAFIA', 'GEOGRAFIA', true);
INSERT INTO CATEGORIA(CATEGORIA_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(10, 'HISTORIA', 'HISTORIA', true);
INSERT INTO CATEGORIA(CATEGORIA_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(11, 'INFORMATICA', 'INFORMATICA', true);
INSERT INTO CATEGORIA(CATEGORIA_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(12, 'LINGÜISTICA', 'LINGÜISTICA', true);
INSERT INTO CATEGORIA(CATEGORIA_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(13, 'LITERATURA', 'LITERATURA', true);
INSERT INTO CATEGORIA(CATEGORIA_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(14, 'MATEMATICAS', 'MATEMATICAS', true);
INSERT INTO CATEGORIA(CATEGORIA_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(15, 'MEDICINA', 'MEDICINA', true);
INSERT INTO CATEGORIA(CATEGORIA_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(16, 'NIÑOS', 'NIÑOS', true);
INSERT INTO CATEGORIA(CATEGORIA_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(17, 'SICOLOGIA', 'SICOLOGIA', true);
INSERT INTO CATEGORIA(CATEGORIA_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(18, 'RELIGION', 'RELIGION', true);
INSERT INTO CATEGORIA(CATEGORIA_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(19, 'SALUD ALTERNATIVA', 'SALUD ALTERNATIVA', true);
INSERT INTO CATEGORIA(CATEGORIA_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(20, 'TEATRO', 'TEATRO', true);
INSERT INTO CATEGORIA(CATEGORIA_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(21, 'TEXTOS ESCOLARES', 'TEXTOS ESCOLARES', true);
INSERT INTO CATEGORIA(CATEGORIA_ID, CLAVE, DESCRIPCION, ACTIVO) VALUES(22, 'TURISMO', 'TURISMO', true);

--Banco
INSERT INTO BANCO(BANCO_ID,NOMBRE,URL_CARGO) VALUES(1,'SANTANDER','www.santander.com');
INSERT INTO BANCO(BANCO_ID,NOMBRE,URL_CARGO) VALUES(2, 'BANCOMER','www.bancomer.com');
INSERT INTO BANCO(BANCO_ID,NOMBRE,URL_CARGO) VALUES(3,'INVERLAT','www.inverlat.com');

--Editoriales
INSERT INTO EDITORIAL(EDITORIAL_ID,NOMBRE,ACTIVO)VALUES(1,'TRILLAS',true);
INSERT INTO EDITORIAL(EDITORIAL_ID,NOMBRE,ACTIVO)VALUES(2,'MC GRAW HILL',true);




